version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "5000:5000"  
    volumes:
    - /app/node_modules
    - .:/app
    stdin_open: true

  redis-server:
    image: 'redis'
